#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config focused_border_color "#98971a"
bspc config border_width         4
bspc config window_gap           36
bspc config split_ratio        0.5

feh --bg-fill ~/dotfiles/wallpaper/wallpaper.png

~/.config/polybar/launch.sh

xsetroot -cursor_name left_ptr
xinput set-prop "ELAN0501:01 04F3:3060" "libinput Natural Scrolling Enabled" 1
xinput set-prop "ELAN0501:01 04F3:3060" "libinput Click Method Enabled" 0 1
xinput set-prop "ELAN0501:01 04F3:3060" "libinput Disable While Typing Enabled" 0

setxkbmap -model thinkpad -layout br
setxkbmap -option caps:swapescape &
